/* REMOVER TODOS OS OBJETOS QUE SERÃO CRIADOS AO EXECUTAR O SCRIPT*/

DROP TABLE JAVA_SERVICO CASCADE CONSTRAINTS;
DROP TABLE JAVA_ENDERECO CASCADE CONSTRAINTS;
DROP TABLE JAVA_CONTATO CASCADE CONSTRAINTS;

/* CRIAÇÃO DA TABELA JAVA_SERVICO*/

CREATE TABLE JAVA_SERVICO(
ID_SERVICO INTEGER NOT NULL,
NOME VARCHAR2(20) NOT NULL,
DESCRICAO VARCHAR(20)
);

ALTER TABLE JAVA_SERVICO ADD CONSTRAINT servico_pk PRIMARY KEY (ID_SERVICO);

/* CRIAÇÃO DA TABELA JAVA_ENDERECO*/

CREATE TABLE JAVA_ENDERECO(
ID_ENDERECO INTEGER NOT NULL,
CEP INTEGER,
COMPLEMENTO VARCHAR2(20) NOT NULL,
NUMERO INTEGER
);

ALTER TABLE JAVA_ENDERECO ADD CONSTRAINT endereco_pk PRIMARY KEY (ID_ENDERECO);

/* CRIAÇÃO DA TABELA JAVA_CONTATO*/

CREATE TABLE JAVA_CONTATO(
ID_CONTATO INTEGER NOT NULL,
TELEFONE INTEGER,
EMAIL VARCHAR(20)
);

ALTER TABLE JAVA_CONTATO ADD CONSTRAINT contato_pk PRIMARY KEY (ID_CONTATO);